project/urls.py
#coding=utf-8


from django.db.models import F, Q
from django.contrib.auth.decorators import login_required

from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

from django.views.generic import ListView, DetailView, UpdateView, CreateView, TemplateView


from depo.models import *
from depo.views import *

from order.models import *
from order.views import *
from meds.views import *
from meds.models import *
from fiskalizacija.models import *
from fiskalizacija.views import *
from sysapp.models import *
from sysapp.views import *
from nabava.models import *
from nabava.views import *

from datetime import datetime, timedelta
import settings


from django.contrib import admin
admin.autodiscover()
 
mjesec_dana = datetime.today()-timedelta(days=3650) 

urlpatterns = patterns('',
    
    url(r'^$', 'handler.views.main'),
    url(r'^autocomplete$', 'handler.views.test'),

    url(r'^admin/', include(admin.site.urls)),
    #url(r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT, }),
    (r'^administrator/', include("project.admin.urls")),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html', }), 


    url(r'^meds/', include('meds.urls')),

    url(r'^client/search$', 'order.views.trazi_korisnika'),
    url(r'^client/view/(?P<pk>\d+)/$', DetailView.as_view(model=Klijent), name="client.view"), 
    url(r'^client/edit/(?P<pk>\d+)/$', UpdateView.as_view(form_class=KlijentForm, model=Klijent, template_name = 'order/klijent_edit.html'), name="client.edit"), 
    url(r'^client/create/$', CreateView.as_view(form_class=KlijentForm, model=Klijent, template_name = 'order/klijent_add.html'), name="client.create"), 
    url(r'^client/browse$', ListView.as_view(model=Klijent, paginate_by=25, queryset=Klijent.objects.filter(tip_klijenta=1)), name="client.browse"),
    url(r'^client/select/(?P<pk>\d+)/$', 'order.views.odaberi_korisnika', name="client.select"),

    url(r'^order/company/view/(?P<pk>\d+)/$', DetailView.as_view(model=Klijent), name="order.tvrtka.view"), 
    url(r'^order/company/edit/(?P<pk>\d+)/$', UpdateView.as_view(form_class=TvrtkaForm, model=Klijent, template_name = 'order/klijent_edit.html'), name="order.tvrtka.edit"), 
    url(r'^order/company/create/$', CreateView.as_view(form_class=TvrtkaForm, model=Klijent, template_name = 'order/klijent_add.html'), name="order.tvrtka.create"), 
    url(r'^order/company/browse$', ListView.as_view(model=Klijent, paginate_by=25, queryset=Klijent.objects.filter(tip_klijenta=2)), name="order.tvrtka.browse"),

    url(r'^order/print/(\d+)$', 'sysapp.views.print_receipt'),
    url(r'^order/print2/(\d+)$', 'sysapp.views.print_receipt_2'),
    url(r'^order/print/racun/njemacki/(\d+)$', 'sysapp.views.print_racun_njemacki'),
    url(r'^order/print/racun/njemacki/broj/(\d+)$', 'sysapp.views.ispis_njemackog_racuna_broj'),
    url(r'^order/print/potvrda/njemacki/(\d+)$', 'sysapp.views.print_potvrda_njemacki'),
    url(r'^order/print/potvrda/o/uplati/njemacki/(\d+)$', 'sysapp.views.print_potvrda_o_uplati_njemacki'),
    url(r'^order/print/racun/za/pristigle/(\d+)$', 'sysapp.views.print_racun_za_pristigle'),
    url(r'^order/print/papiric/(\d+)$', 'sysapp.views.ispis_papirica_za_narudzbu'),

    url(r'^order/print/barcode/(\d+)$', 'sysapp.views.order_print_barcode', name='order.print.barcode'),
    url(r'^order/print/html/(\d+)/$', 'sysapp.views.print_receipt_html'),
    url(r'^order/print/html2/(?P<pk>\d+)/$', DetailView.as_view(model=Narudzba, template_name="order/racun_njemacka.html"), name='order.racun.njemacki_preview'),
    
    url(r'^order/print/shipping/label/(\d+)/$', 'sysapp.views.order_print_shipping_label', name='order.print.shipping.label'),


    url(r'^order/batch/ispis/render$', TemplateView.as_view(template_name='order/batch_ispis_forma.html'), name='order.batch.ispis.render'),

    
    url(r'^order/view/(?P<pk>\d+)/$', DetailView.as_view(model=Narudzba), name='order.view'), 

    url(r'^order/view/sifra/(\d+)/$', 'order.views.narudzba_get_sifra', name='order.view.sifra'), 

    url(r'^order/kosarica/view$', ListView.as_view(model=Kosarica, paginate_by=25), name='order.kosarica.view'), 
    url(r'^order/kosarica/remove/(\d+)$', 'order.views.kosarica_remove', name='order.kosarica.remove'),
    url(r'^order/kosarica/add$', 'order.views.kosarica_add', name='order.kosarica.add'),
    url(r'^order/kosarica/add/alternate$', 'order.views.kosarica_add_alternate', name='order.kosarica.add.alternate'),
    url(r'^order/kosarica/empty$', 'order.views.kosarica_empty', name='order.kosarica.empty'), 
    url(r'^order/kosarica/submit$', 'order.views.kosarica_submit', name='order.kosarica.submit'),
    url(r'^order/kosarica/priceadjust/(\d+)/([\d\.]+)$', 'order.views.kosarica_price_adjust', name='order.kosarica.priceadjust'), 
    url(r'^order/kosarica/qtyadjust/(\d+)/(\d+)$', 'order.views.kosarica_qty_adjust', name='order.kosarica.qtyadjust'), 

   
    url(r'^order/kosarica/add/iz/stare/(\d+)$', 'order.views.kosarica_add_iz_stare_narudzbe', name='order.kosarica.add.iz.stare.narudzbe'),

    url(r'^order/kosarica/naslovna$', 'order.views.kosarica_naslovna', name='order.kosarica.naslovna'),

    

    url(r'^order/posiljka/active/view$', ListView.as_view(model=Narudzba, paginate_by=25, queryset=Narudzba.objects.select_related().filter(posiljka__status=1)), name='order.posiljka.active.view'),

    url(r'^nabava/all/view$', ListView.as_view(model=Nabava, paginate_by=25, queryset=Nabava.objects.all().order_by('-created')), name='nabava.all.view'),
    url(r'^nabava/all/naruci', 'nabava.views.naruci', name='nabava.all.naruci'),
    url(r'^nabava/one/list/(?P<nabava_id>\d+)/$', NabavaItemView.as_view(model=NabavaItem, paginate_by=25), name='nabava.one.list'),
    url(r'^nabava/item/list/(?P<nabava_id>\d+)/(?P<ime>.*)/(?P<trziste>.*)/(?P<std_kolicina>.*)/(?P<jedinice>.*)$', NabavaNarudzbaView.as_view(model=NabavaItem, paginate_by=25, template_name='nabava/nabavanarudzba_list.html'), name='nabava.item.list'),
    url(r'^nabava/one/export/(?P<nabava_id>\d+)/$', 'nabava.views.export_nabava', name='nabava.one.export'),

    url(r'^order/my/depo/list$', ListView.as_view(model=Narudzba, paginate_by=25, queryset=Narudzba.objects.filter(depo=1)), name='order.my.depo.list'),
    url(r'^order/my/depo/today$', MyDepoToday.as_view(model=NarucenArtikal, paginate_by=25, template_name="order/my_depo_today.html"), name='order.my.depo.today'),
    url(r'^order/my/depo/today/zbroji$', MyDepoToday.as_view(model=NarucenArtikal, paginate_by=25, template_name="order/my_depo_today_zbroji.html"), name='order.my.depo.today.zbroji'),

    url(r'^order/my/orders/list$', ListView.as_view(model=Narudzba, paginate_by=25, queryset=Narudzba.objects.filter(depo=0)), name='order.my.orders.list'),
    

    url(r'^order/my/list$', MojeDanasnjeNarudzbe.as_view(model=Narudzba, paginate_by=25, template_name="order/narudzba_my_list.html"), name='order.my.list'),

    url(r'^order/set/konto/(?P<order_id>\d+)/(?P<konto_name>.+)$', 'order.views.order_set_konto', name='order.set.konto'), 
    url(r'^order/vip/status/(?P<order_id>\d+)$', 'order.views.order_vip_status', name='order.vip.status'), 
    url(r'^order/narudzba/storniraj/(\d+)$', 'order.views.order_narudzba_storniraj', name='order.narudzba.storniraj'), 

    url(r'^order/narudzba/izdaj/sve/(\d+)$', 'order.views.order_narudzba_izdaj_sve', name='order.narudzba.izdaj.sve'), 
    url(r'^order/narudzba/naplati/sve/(\d+)$', 'order.views.order_narudzba_naplati_sve', name='order.narudzba.naplati.sve'), 

    url(r'^order/incoming/view$', ListView.as_view(model=NarucenArtikal, paginate_by=25, template_name="order/incoming_view_list.html", queryset=NarucenArtikal.objects.select_related('narudzba').filter(status=0).order_by('ime')), name='order.incoming.view'),
    url(r'^order/artikal/zaprimi/(\d+)/(\d+)$', 'order.views.order_artikal_zaprimi', name='order.artikal.zaprimi'),
    
    url(r'^order/izdavanje/(\d+)/$', 'order.views.order_izdavanje', name='order.izdavanje'),
    url(r'^order/izdavanje/zahtjev/(\d+)/$', 'order.views.order_izdavanje_zahtjev', name='order.izdavanje.zahtjev'), 
    url(r'^order/izdavanje/izdaj/(\d+)/$', 'order.views.order_izdavanje_izdaj', name='order.izdavanje.izdaj'),

    url(r'^order/artikal/izdaj/(\d+)/$', 'order.views.order_artikal_izdaj', name='order.artikal.izdaj'),
    url(r'^order/artikal/naplati/(\d+)/$', 'order.views.order_artikal_naplati', name='order.artikal.naplati'),

    url(r'^order/uplata/add$', 'order.views.order_uplata_add', name="order.uplata.add"), 
    url(r'^order/uplata/delete/(\d+)/(\d+)$', 'order.views.order_uplata_delete', name="order.uplata.delete"), 

    url(r'^order/virman/print/(\d+)$', 'order.views.napravi_virman', name="order.virman.print"), 
    url(r'^order/check/konto/(\d+)$', 'order.views.order_check_konto', name="order.check.konto"), 

    

    url(r'^light/order/incoming/view$', ListView.as_view(model=NarucenArtikal, paginate_by=100, template_name="order/narucenartikal_list_light.html", queryset=NarucenArtikal.objects.select_related('narudzba', 'trziste', 'narucio').filter(~Q(trziste=8), valuta=1).order_by('-created')), name='light.order.incoming.view'), 
    

    
    
    url(r'^sysapp/obavijesti$', ListView.as_view(model=ObavijestiPost, paginate_by=10, template_name="sysapp/obavijesti_list.html", queryset=ObavijestiPost.objects.all().order_by('-created')), name='sysapp.obavijesti'), 
    url(r'^sysapp/ticket/create/$', CreateView.as_view(form_class=TicketForm, model=Ticket, template_name = 'sysapp/ticket_create.html'), name="sysapp.ticket.create"), 
    url(r'^sysapp/ticket/list/$', ListView.as_view(model=Ticket, paginate_by=25, template_name = 'sysapp/ticket_list.html'), name="sysapp.ticket.list"), 

    

    url(r'^order/json/fiskaliziraj/racun/(\d+)/$', 'order.views.order_fiskaliziraj_racun', name='order.fiskaliziraj.racun'), 

project/depo/forms.py
from django import forms

from depo.models import *

from django.forms import Form, ModelForm
from django.forms.formsets import formset_factory

class PosiljkaForm(ModelForm):
  class Meta:
    model = Posiljka

class PosiljkaLijekForm(ModelForm):
  class Meta:
     model = PosiljkaLijek

class ZahtjevForm(Form):
  lijekId = forms.IntegerField()  
  kolicina = forms.IntegerField()
  opaska = forms.CharField(widget=forms.widgets.Textarea(), required=False)

project/templates/depo/inventura_detail.html
<div class="clear space-1x"></div>

<table class="data-table" id="posiljka_prikaz">

    <caption>Na skladištu bi trebalo biti {{paginator.count}} lijekova</caption>
      <thead>
        <tr>
      	   <th>Šifra</th>
           <th>Uneseno</th>
           <th>Izmijenjeno</th>
           <th>Status</th>
           <th>Ime lijeka</th>
        </tr>
      </thead>

	 <tbody>
	
   	{% for i in object_list %}
  	<tr {% if i.nedostaje %}style='opacity:.50;'{%endif%}>
  	  <td><a href="{% url depo.posiljka.kutija.events i.kutija.id %}">{{i.kutija.id}}</a></td>
  	  <td>{{i.created}}</td>
  	  <td>{{i.modified}}</td>
  	  <td>{{i.kutija.ime_statusa}}</td>
  	  <td>{{i.kutija.lijek.lijek.naziv}}</td>
  	</tr>
  	{% endfor %}	                 
	
	
  </tbody>
	
	{% url depo.inventura.detail object_list.0.inventura_id as url %}
	{% include "paginator.html" with adresa=url %}

</table>

project/templates/depo/kosarica_list.html
<img src="/static/img/devel/checkout2.png" style="float: left; margin-bottom: -30px; margin-left: 15px; width: 64px;" />
<div>
<h3>Izdavanje kupcu</h3>
<table class="dt2">

	<!-- Tu ide extends XYZ a osnovni dio izvući da bude zajednički? -->

      
      <thead>
        <tr>
	   	   <th>Naziv</th>           
           <th>Količina</th>           
		   <th>Djelatnik</th>           
           <th>Cijena (&euro;)</th>
           <th>Cijena (kn)</th>
        </tr>
      </thead>

	 <tbody>

	{% for i in object_list %}	  
		<tr class="{% cycle 'odd' 'even' %}">	
			<td>{{i.naziv}}</td>			
			<td>{{i.broj_kutija}}</td>								
		 	<td>{{i.user}}</td>
			<td>{{i.ukupno}} &euro;</td>
			<td>{{i.ukupno_hrk}} kn</td>
		</tr>	  
     {% endfor %}
     
     <tr class="{% cycle 'odd' 'even' %}">	
			<td></td>			
			<td></td>			
			<td></td>					 	
			<td><strong>{{ukupno}} &euro;</strong></td>
			<td><strong>{{ukupno_hrk}} kn</strong></td>
		</tr>       
                       
        </tbody>

	
	{% url depo.stavke.nerijesene as url %}
	{% include "paginator.html" with adresa=url %}

</table>
</div>
<div>
	<a href="{% url depo.kosarica.lock %}"><img src="/static/img/devel/submit3.png" style="width:64px; float:right;margin-right:50px; margin-top:20px;" /></a>
</div>

project/templates/depo/lijek_detail.html
<!-- <img src="/static/img/form/pills2.png" style="float:left;" /> -->


<table class='dt2' style="">

<tr><td>Naziv lijeka:</td><td>{{ lijek.naziv }}</td></tr>
<tr><td>Interna šifra:</td><td> {{ lijek.id }}</td></tr>
<tr><td>Cijena: </td><td>{{ lijek.cijena }} kn</td></tr>
<tr><td>Nabavna cijena: </td><td>{{ lijek.nabavna_cijena_eur }} €</td></tr>
<tr><td>Depo: </td><td>{{ lijek.depo.naziv }}</td></tr>
<tr><td>Na skladištu: </td><td>{{ lijek.stanje }}</td></tr>

</table>

project/templates/depo/lijek_list.html
<table class="data-table" id="popis_lijekova">

      <caption>Depo - Popis Lijekova (str. {{ page_obj.number }} / {{ paginator.num_pages }})</caption>

      <thead>
        <tr>
           <th>ID</th>
	         <th><a href="{% url lijekovi.list.sort toggleorder 'naziv' %}">Naziv</a></th>
           <th><a href="{% url lijekovi.list.sort toggleorder 'cijena' %}">Cijena</a></th>
           <th><a href="{% url lijekovi.list.sort toggleorder 'depo' %}">Depo</a></th>
           <th><a href="{% url lijekovi.list.sort toggleorder 'stanje' %}">Stanje</a></th>
           <th><a href="{% url lijekovi.list.sort toggleorder 'min_stanje' %}">Minimalna zaliha</a></th>
	   {% if perms.is_staff %}
           <th><a href="{% url lijekovi.list.sort toggleorder 'stanje' %}">Stanje kutija</a></th>
           <th></th>
           <th></th>
	   {% endif %}
           <th></th>
           <th></th>
        </tr>
      </thead>

	 <tbody>

	{% for i in object_list %}
		<tr id="lijekovi-stavak-{{i.id}}" class="{% cycle 'odd' 'even' %}">
			<td>{{i.id}}</td>
			<td>{{i.naziv}}</td>
			<td>{{i.cijena}} kn</td>
			<td>{{i.depo}}</td>
			<td>{{i.stanje}}</td>
			<td>{{i.min_stanje}}</td>
			{% if perms.is_staff %}
			<td>{{i.stanje_kutija}}</td>
		 	<td><a href="{% url depo.stanje.kutije i.id %}">Skladišna lista</a></td>
		 	<td><a href="{% url depo.views.graph_lijek_alltime i.id %}">Promet</a></td>
			{% endif %}
		 	<td><a href="{% url depo.lijek.edit i.id %}">Uredi</a></td>
		 	<td>{% if i.ima_dovoljno %}{% else %} <img src="/static/img/table/usklicnik.png" style="width:16px;" /> {%endif%}</td>
		</tr>
        {% endfor %}       


        </tbody>

	{% url lijekovi.list.sort order sortfield as url %}
	{% include "paginator.html" with adresa=url %}

</table>

project/templates/depo/lijek_naruciti_list.html
<!-- <div id="mainTab-6"> -->
<table class="data-table" id="popis_lijekova">


      <caption>Potrebno je naručiti (str. {{ page_obj.number }} / {{ paginator.num_pages }})</caption>

      <thead>
        <tr>
           <th>ID</th>
	   <th>Naziv</th>
           <th>Cijena</th>
           <th>Depo</th>
           <th>Stanje</th>
           <th>Minimalna zaliha</th>
           <th></th>
           <th></th>
        </tr>
      </thead>

	 <tbody>

	{% for i in object_list %}
		<tr id="lijekovi-stavak-{{i.id}}" class="{% cycle 'odd' 'even' %}">
			<td>{{i.id}}</td>
			<td>{{i.naziv}}</td>
			<td>{{i.cijena}} &#8364;</td>
			<td>{{i.depo}}</td>
			<td>{{i.stanje}}</td>
			<td>{{i.min_stanje}}</td>
		 	<td>Uredi</td>
		 	<td>{% if i.ima_dovoljno %}{% else %} <img src="/static/img/table/usklicnik.png" style="width:16px;" /> {%endif%}</td>
		</tr>
        {% endfor %}       
                       
        </tbody>

	{% url depo.zalihe.nedostaje as url %}
	{% include "paginator.html" with adresa=url %}

</table>
<!-- </div> -->

project/templates/depo/lijekkutijaevents_list.html
{% with imeLijeka=object_list.0.kutija.lijek.lijek.naziv kutijaId=object_list.0.kutija.lijek.id barkod=object_list.0.kutija.id %}

<div class="insideTabs">
    <ul class="insideTabsMenu">
       <li><a href="{% url depo.posiljka.kutija.detail kutijaId %}"><< Povratak</a></li>
    </ul> 
    <div class="insideTabsMenuArrow"></div>
</div>
<div class="clear space-1x"></div>

<table class="data-table" id="posiljka_prikaz">

    <caption>{{ imeLijeka }} [{{ barkod }}]</caption>
      <thead>
        <tr>
       	   <th>Djelatnik</th>
           <th>Dogadjaj se desio</th>
           <th>Zadnja izmjena</th>
           <th>Status</th>
        </tr>
      </thead>

	 <tbody>
	 	{% for i in object_list %}
  	<tr>
  	  <td>{{i.user.get_full_name}}</td>
  	  <td>{{i.created}}</td>
  	  <td>{{i.modified}}</td>
  	  <td>{{i.ime_statusa}}</td>
  	</tr>
  	{% endfor %}	                 
	
	</tbody>
	
	{% url depo.posiljka.kutija.events object_list.0.kutija.lijek.id as url %}
	{% include "paginator.html" with adresa=url %}

</table>
{% endwith %}

project/templates/depo/obracun_dnevni.html
<img src="/static/img/devel/checkout2.png" style="float: left; margin-bottom: -30px; margin-left: 15px; width: 64px;" />
<div>
<h3>Dnevni obračun</h3>
<table class="dt2">

	<!-- Tu ide extends XYZ a osnovni dio izvući da bude zajednički? -->

      
      <thead>
        <tr>
	   	   <th>Djelatnik</th>           
	   	   <th>Broj kutija</th>
           <th>Iznos</th>           		   
           <th>Iznos (kn)</th>
        </tr>
      </thead>

	 <tbody>

	{% for i in korisnici %}	  
		<tr class="{% cycle 'odd' 'even' %}">	
			<td>{{i.get_full_name}}</td>			
			<td>{{i.broj_kutija}}</td>
			<td>{% if i.inkasirano.cijena__sum %}{{i.inkasirano.cijena__sum}}{% else %}0{% endif %} &euro;</td>
			<td>{% if i.inkasirano_hrk %}{{i.inkasirano_hrk}}{% else %}0{% endif %} kn</td>
		</tr>	  
     {% endfor %}
     
</table>
</div>
<div>
</div>

project/templates/depo/posiljka_detail.html
<table class="data-table" id="posiljka_dodavanje_prikaz">

    <caption>Artikli</caption>
      <thead>
        <tr>
      	   <th>Naziv</th>
           <th>Cijena</th>
           <th>Komada</th>
           <th>Ukupni iznos</th>
           <th>Zadužio</th>
           <th>Depo</th>           
           <th></th>

        </tr>
      </thead>

	 <tbody>
 	{% for i in posiljka.lijekovi.all %}
	<tr>
	  <td><a href="{% url depo.posiljka.kutija.detail i.id %}">{{i.lijek.naziv}}</a></td>
	  <td>{{i.lijek.cijena}} &euro;</td>
	  <td>{{i.kolicina}}</td>
	  <td>{{i.ukupno}} &euro;</td>
	  <td>{{user.get_full_name}}</td>
	  <td>{{i.lijek.depo.naziv}}</td>	  
	  <td><a class="nohijack" href="javascript:void(0);" onClick="debug_print_click(event, {{i.id}});">Ispis naljepnica</a></td>
	</tr>
	{% endfor %}	                 
	
	<tr><td></td><td></td><td><strong>{{posiljka.broj_artikala}}</strong></td><td><strong>{{posiljka.vrijednost}} &euro;</strong></td><td></td><td></td><td></td></tr>
        </tbody>
	

</table>

project/templates/depo/posiljka_lijek_add.html
<div class="insideTabs">
    <ul class="insideTabsMenu">
       <li><a href="{% url depo.views.posiljka_zakljucaj %}">Zaključaj</a></li>       
    </ul> 
    <div class="insideTabsMenuArrow"></div>
</div>
<div class="clear space-1x"></div>

<div>
           
<form method="post" action="{% url depo.posiljka.lijek.add %}">	

      <img src="/static/img/form/kutija.png" style="float: left; margin-bottom: -50px; margin-left: 10px;" />
      
      <h3 style="padding-left: 80px" >Dodavanje pošiljke (br. {{posiljka.id}} od {{posiljka.datum.date}})</h3>
      
      <table class="dt2">
            
      <thead>
        <tr>
	   <th style="width: 50px;"></th>
           <th>Lijek</th>
	   <th>Količina</th>
	   <th></th>
        </tr>
      </thead>

	 <tbody>	

  	  	<td></td>
  			<td style="padding:0px;">
  			<input style="background: rgba(255, 255, 255, 0); width: 80%; border: 0px; padding: 10px;" data-autocomplete-url="/autocomplete" name="lijek" autofocus="autofocus" type="text" class="autocomplete" id="id_lijek" /></td>
			<td style="padding:0px;"><input style="background: rgba(255, 255, 255, 0); width: 80%; border: 0px; padding: 10px;" class="text-box" type="number" name="kolicina" id="id_kolicina" /></td>
			<td><input type="image" src="/static/img/devel/tick2.png" style="border-style: none;"/></td>
                      
        </tbody>
      </table>
	</form>

</div>


<div class="clear space-2x"></div>

<div id="posiljka_dodavanje_container">

<table class="data-table" id="posiljka_dodavanje_prikaz">

    <caption>Artikli</caption>
      <thead>
        <tr>
      	   <th>Naziv</th>
           <th>Cijena</th>
           <th>Komada</th>
           <th>Ukupni iznos</th>
           <th>Zadužio</th>
           <th>Depo</th>           
           <th></th>

        </tr>
      </thead>

	 <tbody>
 	{% for i in posiljka.lijekovi.all %}
	<tr>
	  <td>{{i.lijek.naziv}}</td>
	  <td>{{i.lijek.cijena}} &euro;</td>
	  <td>{{i.kolicina}}</td>
	  <td>{{i.ukupno}} &euro;</td>
	  <td>{{user.get_full_name}}</td>
	  <td>{{i.lijek.depo.naziv}}</td>	  
	  <td><a href="{% url depo.posiljka.lijek.delete i.id %}">Brisanje</a>
	  </td>
	</tr>
	{% endfor %}	                 
	
	<tr><td></td><td></td><td><strong>{{posiljka.broj_artikala}}</strong></td><td><strong>{{posiljka.vrijednost}} &euro;</strong></td><td></td><td></td><td></td></tr>
        </tbody>
	

</table>


</div>

project/templates/depo/posiljka_list.html
<table class="data-table" id="posiljka_prikaz">

    <caption>Artikli</caption>
      <thead>
        <tr>
      	   <th>Broj</th>
           <th>Datum</th>
           <th>Zadužio</th>
           <th>Broj artikala</th>
           <th>Vrijednost</th>
           <th>Kodirana</th>
        </tr>
      </thead>

	 <tbody>
 	{% for i in object_list %}
	<tr>
	  <td>{{i.id}}</td>
	  
	  <td><a href="{% url depo.posiljka.detail i.id %}">{{i.datum}}</a></td>
	  <td>{{user.get_full_name}}</td>
	  <td>{{i.broj_artikala}}</td>
	  <td>{{i.vrijednost}} &euro;</td>
	  <td>{{i.kodirano}}</td>
	</tr>
	{% endfor %}	                 
	
  </tbody>
	
	{% url depo.posiljka.list as url %}
	{% include "paginator.html" with adresa=url %}

</table>

project/templates/depo/stanje_kutija_list.html
{% with posiljkaLijekId=object_list.0.posiljka.id lijekId=object_list.0.lijek.lijek.id lijek_ime=object_list.0.lijek.lijek.naziv %}

<div class="clear space-1x"></div>

<table class="data-table" id="posiljka_prikaz">

    <caption>Na stanju ima {{object_list.count}} kutija lijeka {{lijek_ime}}</caption>
      <thead>
        <tr>
      	   <th>Šifra</th>
           <th>Uneseno</th>
           <th>Izmijenjeno</th>
           <th>Status</th>
           <th>Ime lijeka</th>
        </tr>
      </thead>

	 <tbody>
	
   	{% for i in object_list %}
  	<tr {% if i.status %}style='opacity:.50;'{%endif%}>
  	  <td><a href="{% url depo.posiljka.kutija.events i.id %}">{{i.id}}</a></td>
  	  <td>{{i.created}}</td>
  	  <td>{{i.modified}}</td>
  	  <td>{{i.ime_statusa}}</td>
  	  <td>{{lijek_ime}}</td>
  	</tr>
  	{% endfor %}	                 
	
	
  </tbody>
	
	{% url depo.stanje.kutije lijekId as url %}
	{% include "paginator.html" with adresa=url %}

</table>
{% endwith %}