project/urls.py
#coding=utf-8


from django.db.models import F, Q
from django.contrib.auth.decorators import login_required

from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

from django.views.generic import ListView, DetailView, UpdateView, CreateView, TemplateView


from depo.models import *
from depo.views import *

from order.models import *
from order.views import *
from meds.views import *
from meds.models import *
from fiskalizacija.models import *
from fiskalizacija.views import *
from sysapp.models import *
from sysapp.views import *
from nabava.models import *
from nabava.views import *

from datetime import datetime, timedelta
import settings


from django.contrib import admin
admin.autodiscover()
 
mjesec_dana = datetime.today()-timedelta(days=3650) 

urlpatterns = patterns('',
    
    url(r'^$', 'handler.views.main'),
    url(r'^autocomplete$', 'handler.views.test'),

    url(r'^admin/', include(admin.site.urls)),
    #url(r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT, }),
    (r'^administrator/', include("project.admin.urls")),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html', }), 


    url(r'^meds/', include('meds.urls')),

    url(r'^client/search$', 'order.views.trazi_korisnika'),
    url(r'^client/view/(?P<pk>\d+)/$', DetailView.as_view(model=Klijent), name="client.view"), 
    url(r'^client/edit/(?P<pk>\d+)/$', UpdateView.as_view(form_class=KlijentForm, model=Klijent, template_name = 'order/klijent_edit.html'), name="client.edit"), 
    url(r'^client/create/$', CreateView.as_view(form_class=KlijentForm, model=Klijent, template_name = 'order/klijent_add.html'), name="client.create"), 
    url(r'^client/browse$', ListView.as_view(model=Klijent, paginate_by=25, queryset=Klijent.objects.filter(tip_klijenta=1)), name="client.browse"),
    url(r'^client/select/(?P<pk>\d+)/$', 'order.views.odaberi_korisnika', name="client.select"),

    url(r'^order/company/view/(?P<pk>\d+)/$', DetailView.as_view(model=Klijent), name="order.tvrtka.view"), 
    url(r'^order/company/edit/(?P<pk>\d+)/$', UpdateView.as_view(form_class=TvrtkaForm, model=Klijent, template_name = 'order/klijent_edit.html'), name="order.tvrtka.edit"), 
    url(r'^order/company/create/$', CreateView.as_view(form_class=TvrtkaForm, model=Klijent, template_name = 'order/klijent_add.html'), name="order.tvrtka.create"), 
    url(r'^order/company/browse$', ListView.as_view(model=Klijent, paginate_by=25, queryset=Klijent.objects.filter(tip_klijenta=2)), name="order.tvrtka.browse"),

    url(r'^order/print/(\d+)$', 'sysapp.views.print_receipt'),
    url(r'^order/print2/(\d+)$', 'sysapp.views.print_receipt_2'),
    url(r'^order/print/racun/njemacki/(\d+)$', 'sysapp.views.print_racun_njemacki'),
    url(r'^order/print/racun/njemacki/broj/(\d+)$', 'sysapp.views.ispis_njemackog_racuna_broj'),
    url(r'^order/print/potvrda/njemacki/(\d+)$', 'sysapp.views.print_potvrda_njemacki'),
    url(r'^order/print/potvrda/o/uplati/njemacki/(\d+)$', 'sysapp.views.print_potvrda_o_uplati_njemacki'),
    url(r'^order/print/racun/za/pristigle/(\d+)$', 'sysapp.views.print_racun_za_pristigle'),
    url(r'^order/print/papiric/(\d+)$', 'sysapp.views.ispis_papirica_za_narudzbu'),

    url(r'^order/print/barcode/(\d+)$', 'sysapp.views.order_print_barcode', name='order.print.barcode'),
    url(r'^order/print/html/(\d+)/$', 'sysapp.views.print_receipt_html'),
    url(r'^order/print/html2/(?P<pk>\d+)/$', DetailView.as_view(model=Narudzba, template_name="order/racun_njemacka.html"), name='order.racun.njemacki_preview'),
    
    url(r'^order/print/shipping/label/(\d+)/$', 'sysapp.views.order_print_shipping_label', name='order.print.shipping.label'),


    url(r'^order/batch/ispis/render$', TemplateView.as_view(template_name='order/batch_ispis_forma.html'), name='order.batch.ispis.render'),

    
    url(r'^order/view/(?P<pk>\d+)/$', DetailView.as_view(model=Narudzba), name='order.view'), 

    url(r'^order/view/sifra/(\d+)/$', 'order.views.narudzba_get_sifra', name='order.view.sifra'), 

    url(r'^order/kosarica/view$', ListView.as_view(model=Kosarica, paginate_by=25), name='order.kosarica.view'), 
    url(r'^order/kosarica/remove/(\d+)$', 'order.views.kosarica_remove', name='order.kosarica.remove'),
    url(r'^order/kosarica/add$', 'order.views.kosarica_add', name='order.kosarica.add'),
    url(r'^order/kosarica/add/alternate$', 'order.views.kosarica_add_alternate', name='order.kosarica.add.alternate'),
    url(r'^order/kosarica/empty$', 'order.views.kosarica_empty', name='order.kosarica.empty'), 
    url(r'^order/kosarica/submit$', 'order.views.kosarica_submit', name='order.kosarica.submit'),
    url(r'^order/kosarica/priceadjust/(\d+)/([\d\.]+)$', 'order.views.kosarica_price_adjust', name='order.kosarica.priceadjust'), 
    url(r'^order/kosarica/qtyadjust/(\d+)/(\d+)$', 'order.views.kosarica_qty_adjust', name='order.kosarica.qtyadjust'), 

   
    url(r'^order/kosarica/add/iz/stare/(\d+)$', 'order.views.kosarica_add_iz_stare_narudzbe', name='order.kosarica.add.iz.stare.narudzbe'),

    url(r'^order/kosarica/naslovna$', 'order.views.kosarica_naslovna', name='order.kosarica.naslovna'),

    

    url(r'^order/posiljka/active/view$', ListView.as_view(model=Narudzba, paginate_by=25, queryset=Narudzba.objects.select_related().filter(posiljka__status=1)), name='order.posiljka.active.view'),

    url(r'^nabava/all/view$', ListView.as_view(model=Nabava, paginate_by=25, queryset=Nabava.objects.all().order_by('-created')), name='nabava.all.view'),
    url(r'^nabava/all/naruci', 'nabava.views.naruci', name='nabava.all.naruci'),
    url(r'^nabava/one/list/(?P<nabava_id>\d+)/$', NabavaItemView.as_view(model=NabavaItem, paginate_by=25), name='nabava.one.list'),
    url(r'^nabava/item/list/(?P<nabava_id>\d+)/(?P<ime>.*)/(?P<trziste>.*)/(?P<std_kolicina>.*)/(?P<jedinice>.*)$', NabavaNarudzbaView.as_view(model=NabavaItem, paginate_by=25, template_name='nabava/nabavanarudzba_list.html'), name='nabava.item.list'),
    url(r'^nabava/one/export/(?P<nabava_id>\d+)/$', 'nabava.views.export_nabava', name='nabava.one.export'),

    url(r'^order/my/depo/list$', ListView.as_view(model=Narudzba, paginate_by=25, queryset=Narudzba.objects.filter(depo=1)), name='order.my.depo.list'),
    url(r'^order/my/depo/today$', MyDepoToday.as_view(model=NarucenArtikal, paginate_by=25, template_name="order/my_depo_today.html"), name='order.my.depo.today'),
    url(r'^order/my/depo/today/zbroji$', MyDepoToday.as_view(model=NarucenArtikal, paginate_by=25, template_name="order/my_depo_today_zbroji.html"), name='order.my.depo.today.zbroji'),

    url(r'^order/my/orders/list$', ListView.as_view(model=Narudzba, paginate_by=25, queryset=Narudzba.objects.filter(depo=0)), name='order.my.orders.list'),
    

    url(r'^order/my/list$', MojeDanasnjeNarudzbe.as_view(model=Narudzba, paginate_by=25, template_name="order/narudzba_my_list.html"), name='order.my.list'),

    url(r'^order/set/konto/(?P<order_id>\d+)/(?P<konto_name>.+)$', 'order.views.order_set_konto', name='order.set.konto'), 
    url(r'^order/vip/status/(?P<order_id>\d+)$', 'order.views.order_vip_status', name='order.vip.status'), 
    url(r'^order/narudzba/storniraj/(\d+)$', 'order.views.order_narudzba_storniraj', name='order.narudzba.storniraj'), 

    url(r'^order/narudzba/izdaj/sve/(\d+)$', 'order.views.order_narudzba_izdaj_sve', name='order.narudzba.izdaj.sve'), 
    url(r'^order/narudzba/naplati/sve/(\d+)$', 'order.views.order_narudzba_naplati_sve', name='order.narudzba.naplati.sve'), 

    url(r'^order/incoming/view$', ListView.as_view(model=NarucenArtikal, paginate_by=25, template_name="order/incoming_view_list.html", queryset=NarucenArtikal.objects.select_related('narudzba').filter(status=0).order_by('ime')), name='order.incoming.view'),
    url(r'^order/artikal/zaprimi/(\d+)/(\d+)$', 'order.views.order_artikal_zaprimi', name='order.artikal.zaprimi'),
    
    url(r'^order/izdavanje/(\d+)/$', 'order.views.order_izdavanje', name='order.izdavanje'),
    url(r'^order/izdavanje/zahtjev/(\d+)/$', 'order.views.order_izdavanje_zahtjev', name='order.izdavanje.zahtjev'), 
    url(r'^order/izdavanje/izdaj/(\d+)/$', 'order.views.order_izdavanje_izdaj', name='order.izdavanje.izdaj'),

    url(r'^order/artikal/izdaj/(\d+)/$', 'order.views.order_artikal_izdaj', name='order.artikal.izdaj'),
    url(r'^order/artikal/naplati/(\d+)/$', 'order.views.order_artikal_naplati', name='order.artikal.naplati'),

    url(r'^order/uplata/add$', 'order.views.order_uplata_add', name="order.uplata.add"), 
    url(r'^order/uplata/delete/(\d+)/(\d+)$', 'order.views.order_uplata_delete', name="order.uplata.delete"), 

    url(r'^order/virman/print/(\d+)$', 'order.views.napravi_virman', name="order.virman.print"), 
    url(r'^order/check/konto/(\d+)$', 'order.views.order_check_konto', name="order.check.konto"), 

    

    url(r'^light/order/incoming/view$', ListView.as_view(model=NarucenArtikal, paginate_by=100, template_name="order/narucenartikal_list_light.html", queryset=NarucenArtikal.objects.select_related('narudzba', 'trziste', 'narucio').filter(~Q(trziste=8), valuta=1).order_by('-created')), name='light.order.incoming.view'), 
    

    
    
    url(r'^sysapp/obavijesti$', ListView.as_view(model=ObavijestiPost, paginate_by=10, template_name="sysapp/obavijesti_list.html", queryset=ObavijestiPost.objects.all().order_by('-created')), name='sysapp.obavijesti'), 
    url(r'^sysapp/ticket/create/$', CreateView.as_view(form_class=TicketForm, model=Ticket, template_name = 'sysapp/ticket_create.html'), name="sysapp.ticket.create"), 
    url(r'^sysapp/ticket/list/$', ListView.as_view(model=Ticket, paginate_by=25, template_name = 'sysapp/ticket_list.html'), name="sysapp.ticket.list"), 

    

    url(r'^order/json/fiskaliziraj/racun/(\d+)/$', 'order.views.order_fiskaliziraj_racun', name='order.fiskaliziraj.racun'), 

project/eskulap/models.py
from django.db import models

# Create your models here.

import settings

class Artikal(models.Model):
    naziv = models.CharField(max_length=128, null=True)
    mj = models.CharField(max_length=10, null=True)
    trziste = models.CharField(max_length=64)
    eskulapid = models.IntegerField(blank=True, null=True)
    pakiranje = models.CharField(max_length=25, null=True)

    class Meta:
        db_table = u'ARTIKLI'

class PonudeZ(models.Model):
    narudzbaid = models.IntegerField(blank=True, null=True)
    datum = models.DateField()
    kupacid = models.IntegerField(blank=True, null=True)
    kupac = models.CharField(max_length=128, null=True)
    adresa = models.CharField(max_length=192, null=True)
    statuseskulap = models.IntegerField(blank=True, null=True)
    statusidema = models.IntegerField(blank=True, null=True)

    class Meta:
        db_table = u'PONUDEZ'

class PonudeS(models.Model):
    ponuda = models.ForeignKey(PonudeZ, null=True, blank=True, related_name='stavke', db_column='ponudaid')
    #ponudaid = models.IntegerField(blank=True, null=True)
    rbr = models.IntegerField(blank=True, null=True)
    artikalid = models.IntegerField(blank=True, null=True)
    trziste = models.CharField(max_length=64)
    kolicina = models.DecimalField(max_digits=10, decimal_places=2)
    mpcijena = models.DecimalField(max_digits=10, decimal_places=2)
    pdv = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        db_table = u'PONUDES'

project/sysapp/models.py
#coding=utf-8

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

from stdnum.iso7064 import mod_11_10 
from django.forms import ModelForm, Textarea, HiddenInput
from django.core.urlresolvers import reverse



def validate_iso7064(value):
  from django.core.validators import ValidationError
  if not mod_11_10.is_valid(value) and value:
    raise ValidationError('Broj je neispravan, molimo provjerite!')




class Temperatura(models.Model):
  timestamp = models.DateTimeField(auto_now_add=True, db_index=True)
  senzor1 = models.FloatField(blank=True, null=True)
  senzor2 = models.FloatField(blank=True, null=True)

class StatusVeze(models.Model):
  cis = models.BooleanField()
  net = models.BooleanField()
  vpn = models.BooleanField()

class UserProfile(models.Model):  
    user = models.OneToOneField(User)  
    

    oib = models.CharField(max_length=64, null=True, blank=True, validators=[validate_iso7064,])
    oznaka_operatera = models.CharField(max_length=64, null=True, blank=True)
    ip = models.IPAddressField(max_length=64, null=True, blank=True)
    oznaka_naplatnog_uredjaja = models.CharField(max_length=64, null=True, blank=True)
    odjel = models.CharField(max_length=64, null=True, blank=True)
    nove_poruke = models.BooleanField(default=0) 
    izdaje = models.BooleanField(default=0) 
 
    def __str__(self):  
          return "%s" % self.user.get_full_name().encode('utf-8') 
 
def create_user_profile(sender, instance, created, **kwargs):  
    if created:  
       profile, created = UserProfile.objects.get_or_create(user=instance)  
 
post_save.connect(create_user_profile, sender=User) 
 
User.profile = property(lambda u: u.get_profile() )


class LoginImage(models.Model):
  user = models.ForeignKey(User)
  password = models.CharField(max_length=128, null=True, blank=True)
  image = models.TextField(null=True,blank=True)
  created = models.DateTimeField(auto_now_add=True)

  def getpng(self):
    return u'<img src="%s" />' % self.image
 
  getpng.allow_tags = True


class InstantMsg(models.Model):
   
  system = models.BooleanField(default=0) 
  broadcast = models.BooleanField(default=0) 
  fetched = models.BooleanField(default=0) 

  msgtype = models.IntegerField(default=0) 
  javascript = models.CharField(max_length=8192, null=True, blank=True) 

  recipient = models.ForeignKey(User, null=True, blank=True, related_name='primljene_poruke')
  sender = models.ForeignKey(User, null=True, blank=True, related_name='poslane_poruke')
   
  naslov = models.CharField(max_length=64, null=True, blank=True)
  sadrzaj = models.CharField(max_length=512, null=True, blank=True)

  def get_absolute_url(self):
    return reverse('sysapp.message.send')                 

class InstantMsgForm(ModelForm):
  class Meta:
    model = InstantMsg
    exclude = ('system', 'fetched', 'msgtype', 'javascript', 'sender',)  
    widgets = {               



      }  

class ObavijestiPost(models.Model):
  created = models.DateTimeField(auto_now_add=True)
  title = models.CharField(max_length=60)
  body = models.TextField()

  def __unicode__(self):
    return self.title

class Ticket(models.Model):
  statusi = {0: 'Otvoreno', 1: 'U postupku', 2: 'Riješeno'}
  status = models.IntegerField(default=0) 
  autor = models.ForeignKey(User, null=True, blank=True, related_name='tickets')
  naslov = models.CharField(max_length=60, blank=True, null=True)
  sadrzaj = models.TextField(blank=True, null=True)
  created = models.DateTimeField(auto_now_add=True)
  
  class Meta:  
    ordering = ['-created']
  
  def get_absolute_url(self):
    return reverse('sysapp.ticket.list')                 

  def get_status(self):
    return self.statusi[self.status]
  
class TicketForm(ModelForm):
  class Meta:
    model = Ticket
    exclude = ('status', 'created',)
    widgets = {
           'sadrzaj': Textarea(attrs={'cols': 20, 'rows': 50}),
           'autor': HiddenInput(attrs={'value': ''}),
      }

project/templates/fiskalizacija/izdaj_nevezan_racun.html
<div>
<a id="ispisi-nevezani" class="nohijack" href="javascript:izdaj_nevezan_fiskalni();$('#ispisi-nevezani').removeAttr('href');show_meds_search();" ><img src="/static/img/devel/push-button3.png" style="margin-left:240px; margin-top:15px; width:128px; opacity:0.85; float:left;"/></a>

<!-- <p style="font-size: 30px; color: lightgrey; margin-left: 400px;">Kliknite na pisač</p> -->
<img src="/static/img/rukaimis.png" style="float:right; margin-top:300px; margin-right:-15px;"/>
<img src="/static/img/dots.png" style="float:right; margin-top:10px; margin-right:15px;"/>
</div>
<script type="text/javascript">

</script>

project/templates/fiskalizacija/obracun.html
 <div class="content-66-left-wrapper" style="border: none;">
<img src="/static/img/devel/checkout2.png" style="float: left; margin-bottom: -20px; margin-left: 15px; width: 64px;" />
  <h3> Obračun na dan {{dan}}.{{mjesec}}.{{godina}}</h3>
  <div class="content-wrapper">

        <table class="dt2">
          <thead>
            <tr>
               <th>Djelatnik</th>           
               <th>Broj računa</th>
               <th>Iznos (kn)</th>
            </tr>
           </thead>

           <tbody>

           {% for i in object_list %}        
             <tr class="{% cycle 'odd' 'even' %}">   
               <td>{{i.get_full_name}}</td>                    
               <td>{{i.broj}}</td>
               <td>{{i.iznos}} kn</td>
             </tr>     
           {% endfor %}
           </tbody>
         </table>

  </div>

 </div>


<div class="content-30-right-wrapper" style="border: none;">
      <div class="content-wrapper">
           
<form method="post" action="{% url fiskalizacija.obracun %}"> 

      <img src="/static/img/devel/calendar.png" style="float: left; margin-bottom: -40px; margin-top: -20px; margin-left: -50px; width:88px;" />
      <table class="dt2">
         <tbody>        
  <tr><td>Dan</td>
  <td><input type="number" name="dan" value="{{dan}}"></td></tr>
  <tr><td>Mjesec</td>
  <td><input type="number" name="mjesec" value="{{mjesec}}"></td></tr>
  <tr><td>Godina</td>
  <td><input type="number" name="godina" value="{{godina}}"></td></tr>
  <tr><td></td><td><input type="submit" value="Pregledaj" class="table-button"></td></tr>
                      
        </tbody>
      </table>
        </form>
	</div>

</div>


<div class="clear space-2x"></div>

project/templates/fiskalizacija/poslovniprostorporuka_add.html
     <img src="/static/img/devel/korisnik5.png" style="float: left; margin-bottom: -50px; margin-left: 60px; width: 96px;" />
<div style="border: 1px dotted gray; width: 450px; box-shadow: 8px 8px 5px #ddd; border-radius: 15px; padding: 30px; margin-top: 30px; margin-left: 85px;" >
	<form id="forma-editiranje-pp" method="post" action="{% url fiskalizacija.pp.add %}" class='modelforms'>
		<table>
		{{ form.as_table }}
		</table>
		<div style="text-align: right;">
		  <input class="modelforms-gumb" type="image" src="/static/img/devel/add2.png" style="width: 64px; border: 0px; margin-right: 20px;" />
		</div>
	</form>
	<div class="clear space-2x" style="height: 1px;"></div>
</div>

project/templates/fiskalizacija/poslovniprostorporuka_detail.html
 <div class="insideTabs">
    <ul class="insideTabsMenu">
       <li><a href="{% url fiskalizacija.pp.list %}">Popis PP poruka</a></li>
       {% if poslovniprostorporuka.http_status != '200' %}
       	<li><a href="{% url fiskalizacija.pp.submit poslovniprostorporuka.id %}">Pošalji u PU</a></li>
       {% endif %}
    </ul>
    <div class="insideTabsMenuArrow"></div>
</div>

<table class="data-table" style="margin-left: 20px; margin-top: 20px; width: 60%;">
       <caption>Fiskalizacija - podaci o poslovnom prostoru {{ poslovniprostorporuka.broj_poslovniprostorporukaa }}</caption>

	<tr><td>OIB Tvrtke:</td><td> {{ poslovniprostorporuka.oib_tvrtke }}</td></tr>
	<tr><td>OIB odgovorne osobe:</td><td> {{ poslovniprostorporuka.oib_odgovornog }}</td></tr>
	<tr><td>Oznaka poslovnog prostora:</td><td> {{ poslovniprostorporuka.oznaka_poslovnog_prostora }}</td></tr>
	<tr><td>Radno vrijeme:</td><td> {{ poslovniprostorporuka.radno_vrijeme }}</td></tr>
	<tr><td>Datum početka primjene:</td><td> {{ poslovniprostorporuka.datum_pocetka_primjene }}</td></tr>
	<tr><td>Ulica:</td><td> {{ poslovniprostorporuka.ulica }}</td></tr>
	<tr><td>Kućni broj:</td><td> {{ poslovniprostorporuka.kucni_broj }}</td></tr>
	<tr><td>Broj pošte:</td><td> {{ poslovniprostorporuka.broj_poste }}</td></tr>
	<tr><td>Naselje:</td><td> {{ poslovniprostorporuka.naselje }}</td></tr>
	<tr><td>Općina:</td><td> {{ poslovniprostorporuka.opcina }}</td></tr>
	<tr><td>Datum i vrijeme:</td><td> {{ poslovniprostorporuka.datum_vrijeme }}</td></tr>
	<tr><td>UUID:</td><td> {{ poslovniprostorporuka.uuid }}</td></tr>
	<tr><td>Fiskaliziran:</td><td> {{ poslovniprostorporuka.fiskaliziran }}</td></tr>	
	<tr><td>Status SOAP zahtjeva:</td><td> {{ poslovniprostorporuka.http_status }}</td></tr>
	<tr><td>Kriptografski potpis OK:</td><td> {{ poslovniprostorporuka.signature_valid }}</td></tr>
</table>

<table class="data-table" style="width: 60%; margin-left: 20px; margin-top: 30px;">
	<caption>Sadržaj komunikacije</caption>
	<tr><td>Zahtjev poreznoj upravi:</td><td><div style="word-wrap: break-word; width: 500px; "> <pre>{{ poslovniprostorporuka.poruka_zahtjev }} </pre></div></td></tr>
	<tr><td>Odgovor porezne uprave:</td><td><div style="word-wrap: break-word; width: 500px; "> <pre>{{ poslovniprostorporuka.poruka_odgovor }} </pre></div></td></tr>

</table>

project/templates/fiskalizacija/poslovniprostorporuka_list.html
<div class="insideTabs">
    <ul class="insideTabsMenu">
       <li><a href="{% url fiskalizacija.pp.add %}">Novi zahtjev PU</a></li>
    </ul>
    <div class="insideTabsMenuArrow"></div>
</div>

<table class="data-table" id="popis-pp-poruka">

      <caption>Poslovni prostor poruke (str. {{ page_obj.number }} / {{ paginator.num_pages }})</caption>

      <thead>
        <tr>
		   <th>UUID</th>
           <th>Ulica</th>
           <th>Kućni broj</th>
           <th>Naselje</th>
           <th>Datum i vrijeme</th>
           <th>Prijavljen PU</th>
           <th>HTTP Status</th>
           <th>Potpis OK</th>
        </tr>
      </thead>

	 <tbody>

	{% for i in object_list %}
		<tr id="klijent-stavak-{{i.id}}" class="{% cycle 'odd' 'even' %}">
   			<td><a href="{% url fiskalizacija.pp.view i.id %}">{{i.uuid}}</a></td>
			<td>{{i.ulica}}</td>
 		    <td>{{i.kucni_broj}}</td>
			<td>{{i.naselje}}</td>
			<td>{{i.datum_vrijeme}}</td>
			<td>{{i.fiskaliziran}}</td>
		 	<td>{{i.http_status}}</td>
                        <td>{% if i.signature_valid %} <img src="/static/img/devel/tick2.png" /> {% else %} <img src="/static/img/devel/iks.png" />{% endif %} </td>
		</tr>
        {% endfor %}       
                       
        </tbody>

	 {% url fiskalizacija.pp.view as url %}
	 {% include "paginator.html" with adresa=url %}

</table>

project/templates/fiskalizacija/zki_kalkulator.html
     <img src="/static/img/mac.png" style="float: left; margin-bottom: -20px; margin-left: 50px; width: 96px; padding-right: 20px;" />
<div style="border: 1px dotted gray; width: 450px; box-shadow: 8px 8px 5px #ddd; border-radius: 15px; padding: 30px; margin-top: 20px; margin-left: 95px;" >
	<h3>ZKI Izračun</h3>
	<form id="forma-zki-calc" method="post" action="{% url fiskalizacija.zki.kalkulator %}" class='modelforms'>
		<table>
<tr><th><label for="id_naziv">OIB:</label></th><td><input id="id_oib" type="text" name="oib" maxlength="256" value="{{oib}}"></td></tr>
<tr><th><label for="id_naziv">Datum i vrijeme: (DD.MM.YYYY HH:MM:SS)</label></th><td><input id="id_datumvrijeme" type="text" name="datumvrijeme" value="{{datumvrijeme}}" maxlength="256" /></td></tr>
<tr><th><label for="id_naziv">Broj</label></th><td><input id="id_broj" type="text" name="broj" maxlength="256" value="{{broj}}" /></td></tr>
<tr><th><label for="id_naziv">Prostor:</label></th><td><input id="id_prostor" type="text" name="prostor" maxlength="256" value="{{prostor}}" /></td></tr>
<tr><th><label for="id_naziv">Uredjaj:</label></th><td><input id="id_uredjaj" type="text" name="uredjaj" maxlength="256" value="{{uredjaj}}" /></td></tr>
<tr><th><label for="id_naziv">Iznos:</label></th><td><input id="id_iznos" type="text" name="iznos" maxlength="256" value="{{iznos}}" /></td></tr>
		</table>
		<div style="text-align: right;">
		  <input class="modelforms-gumb" type="image" src="/static/img/devel/kvacica.png" style="width: 64px; border: 0px; margin-right: 20px;" />
		</div>
	</form>
	<div class="clear space-2x" style="height: 1px;"></div>
	{% if zki %}<h3>ZKI: {{ zki }} </h3>{% endif %}
</div>